import fs from "fs";

export interface BenchmarkResult {
  completed: number;
  failed: number;
  metrics: {
    min: number;
    max: number;
    avg: number;
    p95: number;
    p99: number;
  };
}

export function exportJSON(result: BenchmarkResult, filePath: string) {
  fs.writeFileSync(filePath, JSON.stringify(result, null, 2));
  console.log(`📦 JSON report saved to ${filePath}`);
}

export function exportMarkdown(result: BenchmarkResult, filePath: string) {
  const md = `
# DevPulse Benchmark Report

| Metric | Value |
|--------|-------|
| ✔ Completed | ${result.completed} |
| ✖ Failed | ${result.failed} |
| ⏱ Avg | ${result.metrics.avg.toFixed(2)} ms |
| 📉 Min | ${result.metrics.min.toFixed(2)} ms |
| 📈 Max | ${result.metrics.max.toFixed(2)} ms |
| 🎯 p95 | ${result.metrics.p95.toFixed(2)} ms |
| 🎯 p99 | ${result.metrics.p99.toFixed(2)} ms |

Generated by **DevPulse** 🔁
`;

  fs.writeFileSync(filePath, md.trim());
  console.log(`📝 Markdown report saved to ${filePath}`);
}
